apiVersion: 1
datasources:
  - name: GameHeist InfluxDB
    uid: heist-influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: gameheist
      defaultBucket: heist_metrics
    secureJsonData:
      token: $INFLUX_TOKEN
